title: Cristiano Cunha personal blog on automation and testing.
description: > # this means to ignore newlines until "baseurl:"
  Thoughts on automation and testing.
permalink: ':title/'
baseurl: #"/blog" #"/flexible-jekyll" # the subpath of your site, e.g. /blog
url: "http://cristianomcunha.com" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Cristiano Cunha # add your name
author-img: cristiano-cunha.jpg # add your photo
about-author: I am a tester focusing on automation. Always hungry to keep learning. # add description
social-twitter: melioth # add your Twitter handle
social-facebook: cristiano.morais.cunha # add your Facebook handle
social-github: cmcunha # add your Github handle
social-linkedin: cristianomcunha# add your Linkedin handle
social-email: cristianocunhablog@gmail.com# add your Email address

# Disqus
discus-identifier: cristianomcunha-com # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
remote_theme: artemsheludko/flexible-jekyll
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
