title: Hello, world! I'm Cristiano Cunha
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/blog" #"/flexible-jekyll" # the subpath of your site, e.g. /blog
url: "www.cristianomcunha.com" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Cristiano Cunha # add your name
author-img: cristiano-cunha.jpg # add your photo
about-author: I am a tester focusing on automation. Always hungry to keep learning. # add description
social-twitter: melioth# add your Twitter handle
social-facebook: cristiano.morais.cunha # add your Facebook handle
social-github: cmcunha # add your Github handle
social-linkedin: cristianomcunha# add your Linkedin handle
social-email: cristianocunhablog@gmail.com# add your Email address

# Disqus
discus-identifier: cmcunha # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
remote_theme: artemsheludko/flexible-jekyll
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
